### PR TITLE
initial core-markup commit

### PR DESCRIPTION
**Pull request by Brecert**
- adds MessageQuotes, and CustomEmoji to the marku

### CODE REVIEW

**Comment by supertiger1234** [comment]
reverted back*** to my ugly code, i should say.

**Comment by supertiger1234** [comment]
seems like large-emoji is not working properly but youre probably aware of this 😅

**Comment by Brecert** [comment]
before this is added, we should review the npm lockfile, because the size of it seems a little too large

**Comment by supertiger1234** [comment]
hm its also large in the master branch of nertivia ts after running npm i. hmm

**Comment by supertiger1234** [comment]
since its also large in the master branch, I think I'm gonna hit the merge button, thanksss btww :D

**Pull request merged**
